/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practica2;

/**
 *
 * @author felix
 */
public class GameFrame extends javax.swing.JFrame {

    /**
     * Creates new form GameFrame
     */
    private ControlJuego control;
    public GameFrame() {
        control = new ControlJuego();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rellenarMazo = new javax.swing.JButton();
        sacarCartasBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sacarCartasTexto = new javax.swing.JTextField();
        meterCartasBoton = new javax.swing.JButton();
        meterCartasTexto = new javax.swing.JTextField();
        manoCarta1 = new javax.swing.JLabel();
        manoCarta2 = new javax.swing.JLabel();
        manoCarta3 = new javax.swing.JLabel();
        manoCarta4 = new javax.swing.JLabel();
        manoCarta5 = new javax.swing.JLabel();
        manoCarta6 = new javax.swing.JLabel();
        manoCarta7 = new javax.swing.JLabel();
        manoCarta8 = new javax.swing.JLabel();
        manoCarta9 = new javax.swing.JLabel();
        manoCarta10 = new javax.swing.JLabel();
        pozoCarta1 = new javax.swing.JLabel();
        pozoCarta2 = new javax.swing.JLabel();
        pozoCarta3 = new javax.swing.JLabel();
        pozoCarta4 = new javax.swing.JLabel();
        pozoCarta5 = new javax.swing.JLabel();
        pozoCarta6 = new javax.swing.JLabel();
        pozoCarta7 = new javax.swing.JLabel();
        pozoCarta8 = new javax.swing.JLabel();
        pozoCarta9 = new javax.swing.JLabel();
        pozoCarta10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rellenarMazo.setText("Descartar mazo");
        rellenarMazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rellenarMazoActionPerformed(evt);
            }
        });

        sacarCartasBoton.setText("Sacar cartas");
        sacarCartasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacarCartasBotonActionPerformed(evt);
            }
        });

        jLabel1.setText("Pozo:");

        jLabel2.setText("Mano:");

        meterCartasBoton.setText("Meter cartas");
        meterCartasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meterCartasBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pozoCarta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pozoCarta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pozoCarta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pozoCarta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pozoCarta5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pozoCarta6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pozoCarta7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pozoCarta8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pozoCarta9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pozoCarta10, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(manoCarta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(manoCarta2, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                            .addGap(160, 160, 160)
                            .addComponent(rellenarMazo))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(manoCarta4, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addComponent(manoCarta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(manoCarta5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sacarCartasTexto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(meterCartasTexto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(meterCartasBoton)
                                .addComponent(sacarCartasBoton))
                            .addGap(7, 7, 7)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(manoCarta10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addComponent(manoCarta9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manoCarta8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manoCarta7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manoCarta6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(rellenarMazo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sacarCartasBoton)
                            .addComponent(sacarCartasTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manoCarta3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(meterCartasBoton)
                                    .addComponent(meterCartasTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(manoCarta4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(manoCarta5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manoCarta6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manoCarta7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manoCarta8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manoCarta9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manoCarta10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manoCarta1)
                            .addComponent(pozoCarta1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manoCarta2)
                            .addComponent(pozoCarta2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pozoCarta3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pozoCarta4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pozoCarta5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pozoCarta6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pozoCarta7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pozoCarta8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pozoCarta9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pozoCarta10)))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rellenarMazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rellenarMazoActionPerformed
        // TODO add your handling code here:
        control.llenarPozo();
        mostrarPozo();
        
    }//GEN-LAST:event_rellenarMazoActionPerformed

    public void mostrarPozo ()
    {
        Pila<Carta> aux = new Pila(10);
        int contador = 1;
        //encontrarManoCarta(1).setText("Funcionó!");
        //System.out.println("UNOUNONONONONONONONO");
        while (control.getPozo().isEmpty() == false && contador <= 10)
        {
            encontrarPozoCarta(contador).setVisible(true);
            encontrarPozoCarta(contador).setText(control.getPozo().peek().toString());
            aux.push(control.getPozo().pop());
            contador += 1;
        }
        //System.out.println("DODODODODODOS");
        while (aux.isEmpty() == false)
        {
            control.getPozo().push(aux.pop());
        }
        //System.out.println("TRESESESESESESEES");
        while (contador <= 10)
        {
            encontrarPozoCarta(contador).setVisible(false);
            System.out.println("ContadorPOZO: " + contador);
            contador += 1;
        }
        //control.imprimirPozo();
        //System.out.println("CUATRORORORORORORORO");
    }
    public void mostrarMano ()
    {
        Pila<Carta> aux = new Pila(10);
        int contador = 1;
        while (control.getMano().peek() != null && contador <= 10)
        {
            encontrarManoCarta(contador).setVisible(true);
            encontrarManoCarta(contador).setText(control.getMano().peek().toString());
            aux.push(control.getMano().pop());
            contador += 1;
        }
        while (aux.isEmpty() == false)
        {
            control.getMano().push(aux.pop());
        }
        while (contador <= 10)
        {
            encontrarManoCarta(contador).setVisible(false);
            System.out.println("ContadorDEMANO: " + contador);
            contador += 1;
        }
        //control.imprimirMano();
    }
    private void sacarCartasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacarCartasBotonActionPerformed
        // TODO add your handling code here:
        String texto = sacarCartasTexto.getText();
        System.out.println(texto);
        if (texto.length() == 1)
        {
            control.sacarDePozo(texto.charAt(0));
        }
        else
        {
            control.sacarDePozo(texto);
        }
       //control.imprimirMano();
        mostrarMano();
        mostrarPozo();
    }//GEN-LAST:event_sacarCartasBotonActionPerformed
    public void limpiar ()
    {
        System.out.print("\033[H\033[2J");  
        System.out.flush(); 
    }
    private void meterCartasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meterCartasBotonActionPerformed
        // TODO add your handling code here:
        limpiar();
        String texto = meterCartasTexto.getText();
        System.out.println("Meter carta: " + texto);
        System.out.println("MANOS");
        control.imprimirMano();
        System.out.println("POZO:");
        control.imprimirPozo();
        if (texto.length() == 1)
        {
            control.meterAlPozo(texto.charAt(0));
        }
        else
        {
            control.meterAlPozo(texto);
        }
        System.out.println("Aqui mostramos:");
        System.out.println("MANOS 2222222222222222");
        control.imprimirMano();
        System.out.println("POZO:22222222222222222222");
        control.imprimirPozo();
        mostrarMano();
        mostrarPozo();
        
    }//GEN-LAST:event_meterCartasBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame().setVisible(true);
            }
        });
    }
    public javax.swing.JLabel encontrarManoCarta(int index)
    {
        switch (index)
        {
            case 1:
                return manoCarta1;
            case 2:
                return manoCarta2;
            case 3:
                return manoCarta3;
            case 4:
                return manoCarta4;
            case 5:
                return manoCarta5;
            case 6:
                return manoCarta6;
            case 7:
                return manoCarta7;
            case 8:
                return manoCarta8;
            case 9:
                return manoCarta9;
            case 10:
                return manoCarta10;
            default:
                return null;
        }
    }
    public javax.swing.JLabel encontrarPozoCarta(int index)
    {
        switch (index)
        {
            case 1:
                return pozoCarta1;
            case 2:
                return pozoCarta2;
            case 3:
                return pozoCarta3;
            case 4:
                return pozoCarta4;
            case 5:
                return pozoCarta5;
            case 6:
                return pozoCarta6;
            case 7:
                return pozoCarta7;
            case 8:
                return pozoCarta8;
            case 9:
                return pozoCarta9;
            case 10:
                return pozoCarta10;
            default:
                return null;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel manoCarta1;
    private javax.swing.JLabel manoCarta10;
    private javax.swing.JLabel manoCarta2;
    private javax.swing.JLabel manoCarta3;
    private javax.swing.JLabel manoCarta4;
    private javax.swing.JLabel manoCarta5;
    private javax.swing.JLabel manoCarta6;
    private javax.swing.JLabel manoCarta7;
    private javax.swing.JLabel manoCarta8;
    private javax.swing.JLabel manoCarta9;
    private javax.swing.JButton meterCartasBoton;
    private javax.swing.JTextField meterCartasTexto;
    private javax.swing.JLabel pozoCarta1;
    private javax.swing.JLabel pozoCarta10;
    private javax.swing.JLabel pozoCarta2;
    private javax.swing.JLabel pozoCarta3;
    private javax.swing.JLabel pozoCarta4;
    private javax.swing.JLabel pozoCarta5;
    private javax.swing.JLabel pozoCarta6;
    private javax.swing.JLabel pozoCarta7;
    private javax.swing.JLabel pozoCarta8;
    private javax.swing.JLabel pozoCarta9;
    private javax.swing.JButton rellenarMazo;
    private javax.swing.JButton sacarCartasBoton;
    private javax.swing.JTextField sacarCartasTexto;
    // End of variables declaration//GEN-END:variables
}
